@startuml
class controller{
    +buttonAdd
    +buttonRem
    +buttonCls
    +buttonEdit
    +buttonSave
    +buttonLoad
    +tableview
    +textFieldSearch
    +buttonHelp
}

class save{
    +save
    +saveAsJson
    +saveAsHtml
    +saveAsText
}

class load{
    +load
    +loadAsJson
    +loadAsHtml
    +loadAsText
}

class InventoryManagementApplication{
    +start
    +main
}

class MineItemData{
    -mineName
    -mineValue
    -mineSerial
    +MineItemData
    +getName
    +setName
    +getValue
    +setValue
    +getSerial
    +setSerial
}

InventoryManagementApplication -- controller
controller -- MineItemData
controller -- save
controller -- load



@enduml